<?php

// Database constants...
define("DB_HOST","localhost");       // host name...
define("DB_USER","root");       // user name for DB...
define("DB_PASSWORD","123");   // password for DB...
define("DB_NAME","contact_manager");       // DB name...

// constants for names of data tables...
define("CONTACTS_DB", "contacts");
define("USERS_DB", "users");

// pagination constants...
define("MAX_ON_PAGE", 5);     // number of contacts on page...

// constants for images...
define("IMG_SORT_BY_DESC", "/img/DESC.png");     // path to picture of sorting by DESC
define("IMG_SORT_BY_ASC", "/img/ASC.png");      // path to picture of sorting by ASC

// constants for images...
define("SITE", "http://contactmanager.test/");     // main site...
