<?php

// Database constants...
define("DB_HOST","localhost");       // host name...
define("DB_USER","root");       // user name for DB...
define("DB_PASSWORD","123");   // password for DB...
define("DB_NAME","contact_manager");       // DB name...

// constants for names of data tables...
define("CONTACTS_DB", "contacts");
define("USERS_DB", "users");
